### ISSUE TITLE
Create a settings.gradle file and set rootProject.name there

### ISSUE THREAD

**Issue by DiegoPino** [uml-digitalinitiatives/derivative-route#1]
Proposing the use of `rootProject.name` inside settings.gradle file to allow the project name to be independent of the containing directory, ensuring that way that install and reference to this feature stays consistent even when published in Github under different names, cloned and renamed, etc.

Also, good way to control the artifacts name (maybe useful) could be the use inside `build.gradle` of 
`project.archivesBaseName = 'some-name'`

**Comment by whikloj** [comment]
👍 
Resolved with f41d585fdb7b90722eeda703eedd63b08d58e55a
